# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=5120']
    -   id: check-docstring-first
    -   id: name-tests-test
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-case-conflict
-   repo: https://github.com/pycqa/flake8
    rev: '7.2.0'
    hooks:
    -   id: flake8
        exclude: (tests|.*_mixins.*)
        additional_dependencies:
        - flake8-docstrings
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-no-pep420
        - flake8-tidy-imports
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.12
-   repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
    -   id: bandit
        exclude: (tests|.*_mixins.*)
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
# -   repo: https://github.com/astral-sh/ruff-pre-commit
#     # Ruff version.
#     rev: v0.8.0
#     hooks:
#     # Run the linter.
#     -   id: ruff
#         args: [ --fix ]
#     # Run the formatter.
#     -   id: ruff-format
# -   repo: https://github.com/pycqa/isort
#     rev: 5.11.2
#     hooks:
#     -   id: isort
#         name: isort (python)
#     -   id: isort
#         name: isort (cython)
#         types: [cython]
#     -   id: isort
#         name: isort (pyi)
#         types: [pyi]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: "1.24.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.1"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.4
    hooks:
    -   id: rstcheck
